- name: Install nginx
  yum:
    name: nginx
    state: installed

- name: Remove the old file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: copy the file
  copy:
   src: /tmp/frontend-main/static/
   dest: /usr/share/nginx/html/
   remote_src: yes

- name: copy config file
  copy:
    src: robohop.conf
    dest: /etc/nginx/default.d/robohop.conf

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Download and Extract Frontend content
  include_role:
    name: common
    tasks_from: download