#!/usr/bin/bash
#A=10
#echo B = $A
#Date=20-02-2022
#echo welcome, to day date = ${Date}

#commnd line substitution

#NoOfUsers=$(who |wc -l)
#echo no of users = ${NoOfUsers}

read -p 'enter '  name
echo your name = $name