- name: Install NodeJS
  yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add application user
  user:
    name: roboshop

- name: Download from github
  include_tasks:
    file: download.yml

- name: copy the file
  copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install npm
  community.general.npm:
    path: /home/roboshop/catalogue
    state: latest
  become_user: roboshop