- name: Roboshop frontend setup
  hosts: Frontend
  become: yes
  roles:
    - name: frontend

- name: RoboShop MongoDB Setup
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
    - name: mongodb