- name: Roboshop frontend setup
  hosts: Frontend
  become: yes
  tags: frontend
  roles:
    - name: frontend

- name: RoboShop MongoDB Setup
  hosts: MONGODB
  become: yes
  tags: mongodb
  roles:
    - name: mongodb

- name: RoboShop catalogue Setup
  hosts: catalogue
  become: yes
  tags: catalogue
  roles:
    - name: catalogue

- name: RoboShop redis Setup
  hosts: redis
  become: yes
  tags: redis
  roles:
    - name: redis

- name: RoboShop user Setup
  hosts: user
  become: yes
  tags: user
  roles:
    - name: user