help:
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'

frontend:
	@echo Installing frontend

catalogue:
	@echo Installing catalogue

cart:
	@echo Installing cart

mongodb:
	@echo Installing mongodb

mysql:
	@echo Installing mysql

payment:
	@echo Installing payment

rabbitmq:
	@echo Installing rabbitmq

redis:
	@echo Installing redis

shipping:
	@echo Installing shipping

user:
	@echo Installing user