frontend:
	@echo installing frontend
catalouge:
	@echo installing catalouge
cart:
	@echo installing cart
mongodb:
	@echo installing mongodb
mysql:
	@echo installing mysql
payment:
	@echo installing payment
rabbitmq:
	@echo installing rabbitmq
redis:
	@echo installing redis
shipping:
	@echo installing shipping
user:
	@echo installing user

